DROP TABLE EMP_BOARDS CASCADE CONSTRAINTS;
DROP SEQUENCE EMP_BOARDS_SEQ;

CREATE TABLE EMP_BOARDS (
	  ID NUMBER NOT NULL
	, TITLE VARCHAR2(100) NOT NULL
	, CONTENT VARCHAR2(2000)
	, EMPID NUMBER NOT NULL
	, CREATEDATE DATE DEFAULT(SYSDATE)
	, VIEW_CNT NUMBER DEFAULT(0)
	, "LIKE" NUMBER DEFAULT(0)
	, CONSTRAINT EMP_BOARDS_ID_PK PRIMARY KEY (ID)
	, CONSTRAINT EMP_BOARDS_EMP_ID_FK FOREIGN KEY (EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

/* 기존 테이블의 데이터를 유지하고 싶으면 이 구문을 실행해서 수정하세요.
ALTER TABLE EMP_BOARDS ADD VIEW_CNT NUMBER DEFAULT(0);
ALTER TABLE EMP_BOARDS ADD "LIKE" NUMBER DEFAULT(0);
*/

CREATE SEQUENCE EMP_BOARDS_SEQ NOCACHE;

INSERT INTO EMP_BOARDS VALUES(EMP_BOARDS_SEQ.NEXTVAL, '테스트 제목', '테스트 내용', 100, SYSDATE);

DROP TABLE EMP_BOARDS_STATISTICS;
DROP SEQUENCE EMP_BOARDS_STATISTICS_SEQ;

CREATE TABLE EMP_BOARDS_STATISTICS (
	   ID NUMBER PRIMARY KEY
	 , EMPID NUMBER
	 , BID NUMBER
	 , ISVIEW VARCHAR2(1) CHECK(ISVIEW IN ('Y', 'N'))
	 , LASTEST_DATE1 DATE
	 , ISLIKE VARCHAR2(1) CHECK(ISLIKE IN ('Y', 'N'))
	 , LASTEST_DATE2 DATE
	 , CONSTRAINT EMP_BOARDS_STATISTICS_EMPID_FK FOREIGN KEY(EMPID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
	 , CONSTRAINT EMP_BOARDS_STATISTICS_BID_FK FOREIGN KEY(BID) REFERENCES EMP_BOARDS(ID)
);

CREATE SEQUENCE EMP_BOARDS_STATISTICS_SEQ NOCACHE;