SELECT * FROM ALL_ALL_TABLES WHERE TABLE_NAME = 'EMPLOYEES';

-- 관리자 계정으로 접속 후 PUSER1 소유의 EMPLOYEES 테이블 조회 -> 지칭해야함
SELECT * FROM PUSER1.EMPLOYEES;

-- 관리자 계정으로 실행 후 PUSER1 에게 동의어를 생성할 수 있는 권한 부여
GRANT CREATE SYNONYM TO PUSER1;
COMMIT;


-- PUSER1 계정으로 별칭 부여
CREATE SYNONYM EMP FOR EMPLOYEES;

-- PUSER1 로 확인
SELECT * FROM EMPLOYEES;
SELECT * FROM EMP;

-- 관리자 계정으로 확인
SELECT * FROM PUSER1.EMP;
SELECT * FROM PUSER1.EMPLOYEES;

-- 관리자 계정으로 공개 동의어 생성
CREATE PUBLIC SYNONYM EMP FOR PUSER1.EMPLOYEES;
CREATE PUBLIC SYNONYM DEP FOR PUSER1.DEPARTMENTS;

-- 권한 부여
GRANT SELECT ON EMP TO DEVADMIN;
GRANT SELECT ON DEP TO DEVADMIN;

-- SELECT 권한 제거
REVOKE SELECT ANY TABLE FROM DEVADMIN;

SELECT * FROM EMP;
SELECT * FROM DEP;




