CREATE TABLE SAMPLE(
	   ID		NUMBER						PRIMARY KEY
	 , NAME 	VARCHAR2(30)				NOT NULL
	 , GENDER	CHAR(1)						CHECK(GENDER IN ('F', 'M'))
	 , AGE		NUMBER			DEFAULT(0) 	NOT NULL
);

INSERT INTO SAMPLE(ID, NAME, GENDER, AGE) VALUES(1, '홍길동', 'M', 27);
INSERT INTO SAMPLE(ID, NAME, GENDER, AGE) VALUES(2, '김주영', 'M', 30);
INSERT INTO SAMPLE(ID, NAME, GENDER		) VALUES(3, '박수안', 'F'	   );
INSERT INTO SAMPLE(ID, NAME, GENDER, AGE) VALUES(4, '이종석', 'M', 25);

-- 디폴트 지정
-- INSERT INTO SAMPLE VALUES(5, '최설은', 'F'); -> 에러
INSERT INTO SAMPLE VALUES(5, '최설은', 'F', DEFAULT);


-- OR REPLACE : 생성한 뷰가 존재하면 뷰를 갱신함
CREATE OR REPLACE VIEW V_SAMPLE
	AS SELECT ID
			, NAME
			, GENDER
			, AGE
		 FROM SAMPLE
		WHERE AGE BETWEEN 20 AND 29
	WITH READ ONLY;
--	WITH CHECK OPTION; 

-- INSERT INTO V_SAMPLE VALUES(6, '곽종수', F, 30);

INSERT INTO V_SAMPLE VALUES(6, '곽종수', 'F');
INSERT INTO V_SAMPLE VALUES(7, '김도연', 'F', 23);

-- CHECK OPTION 조건에 위배되는 코드 (에러)
-- UPDATE V_SAMPLE
--    SET AGE = 35
--  WHERE ID = 1;

 UPDATE V_SAMPLE
    SET AGE = 21
  WHERE ID = 1;

-- 확인
COMMIT;
SELECT * FROM SAMPLE;
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM V_SAMPLE;




DROP SEQUENCE SEQ_TEST;

CREATE SEQUENCE SEQ_TEST
		  START WITH 300
	  INCREMENT BY	   5
	   MAXVALUE		 310
	   MINVALUE 	 250
	      CYCLE
	   	  CACHE 5;
	   
SELECT SEQ_TEST.NEXTVAL FROM DUAL;

SELECT SEQ_TEST.CURRVAL FROM DUAL;

SELECT NVL(NULL, 'Hello') FROM DUAL;

SELECT * FROM USER_SEQUENCES  WHERE SEQUENCE_NAME = 'SEQ_TEST';

DROP SEQUENCE SEQ_SAMPLE;
CREATE SEQUENCE SEQ_SAMPLE START WITH 7 NOCACHE;

SELECT * FROM SAMPLE;
INSERT INTO SAMPLE VALUES(SEQ_SAMPLE.NEXTVAL, '시퀀스', 'F', 0);
DELETE FROM SAMPLE WHERE ID = 12;	-- 빈 부분을 채우지는 않음




