SELECT 10 * NVL(NULL, 0) AS Col1
	FROM DUAL;
	

SELECT COUNTRY_ID 
	,  COUNTRY_NAME
	,  DECODE(COUNTRY_ID, 'IT', '이태리', 'JP', '일본', 'US', '미국', 'CA', '캐나다', COUNTRY_NAME) AS COUNTRY_KOR
	FROM COUNTRIES;
	

-- 소득분류 라는 새로운 컬럼 생성
-- 급여에 따라 하위소득, 중위소득, 고소득, 미분류 로 나눈다.
SELECT EMPLOYEE_ID
	,  FIRST_NAME 
	,  LAST_NAME 
	,  CASE WHEN SALARY <= 1000 AND SALARY < 3000 THEN '하위소득'
			WHEN SALARY <= 3000 AND SALARY < 6000 THEN '중위소득'
			WHEN SALARY <= 6000 AND SALARY < 10000 THEN '고소득'
			ELSE '미분류'
		END AS "소득분류"
	FROM EMPLOYEES;
	

-- 전체 직원의 급여 합
SELECT SUM(SALARY)
	FROM EMPLOYEES; 
	

-- 전체 직원의 급여 평균
SELECT AVG(SALARY)
	FROM EMPLOYEES;
	

-- NULL 데이터가 포함된 컬럼의 평균
SELECT AVG(COMMISSION_PCT)  
	FROM EMPLOYEES
	WHERE COMMISSION_PCT IS NOT NULL;
	

-- 최소값
SELECT MIN(COMMISSION_PCT)
	,  MIN(HIRE_DATE)
	,  MIN(FIRST_NAME) 
	FROM EMPLOYEES;
	

-- 최대값
SELECT MAX(COMMISSION_PCT)
	,  MAX(HIRE_DATE)
	,  MAX(FIRST_NAME) 
	FROM EMPLOYEES;


-- 갯수
SELECT COUNT(*)
	FROM EMPLOYEES
	WHERE COMMISSION_PCT IS NULL;
